[metadata.heroku]
  root-package = "github.com/bitrise-io/identity-info-server"
  ensure = "false"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.0"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"
